// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Soccer.Server.Data;

#nullable disable

namespace Soccer.Server.Migrations
{
    [DbContext(typeof(AppContextDb))]
    [Migration("20250503190551_FixUserIdMapping2")]
    partial class FixUserIdMapping2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Soccer.Server.Models.Competitions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CompetitionName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("competition_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<long>("NumberOfTeams")
                        .HasColumnType("bigint")
                        .HasColumnName("number_of_teams");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<long>("creator_id")
                        .HasColumnType("bigint")
                        .HasColumnName("creator_id");

                    b.HasKey("Id");

                    b.HasIndex("creator_id");

                    b.ToTable("competitions", (string)null);
                });

            modelBuilder.Entity("Soccer.Server.Models.Match", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<long>("away_team_id")
                        .HasColumnType("bigint")
                        .HasColumnName("away_team_id");

                    b.Property<long>("competition_id")
                        .HasColumnType("bigint")
                        .HasColumnName("competition_id");

                    b.Property<long>("home_team_id")
                        .HasColumnType("bigint")
                        .HasColumnName("home_team_id");

                    b.HasKey("Id");

                    b.HasIndex("away_team_id");

                    b.HasIndex("competition_id");

                    b.HasIndex("home_team_id");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("Soccer.Server.Models.Participant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<long>("competition_id")
                        .HasColumnType("bigint")
                        .HasColumnName("competition_id");

                    b.Property<long>("members_id")
                        .HasColumnType("bigint")
                        .HasColumnName("members_id");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("competition_id");

                    b.HasIndex("members_id");

                    b.HasIndex("user_id");

                    b.ToTable("participants", (string)null);
                });

            modelBuilder.Entity("Soccer.Server.Models.Posts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("LOCALTIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("post_description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("post_title");

                    b.Property<string>("PostType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("News")
                        .HasColumnName("post_type");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("user_id");

                    b.ToTable("posts", (string)null);
                });

            modelBuilder.Entity("Soccer.Server.Models.Recipe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ingredients");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("instructions");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("Soccer.Server.Models.Teams", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("LOCALTIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("logo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("LOCALTIMESTAMP");

                    b.Property<long>("owner_id")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_id");

                    b.HasKey("Id");

                    b.HasIndex("owner_id");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("Soccer.Server.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("LOCALTIMESTAMP");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("ProfileImage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("..\\wwwroot\\Assert\\default-image.png")
                        .HasColumnName("profile_image");

                    b.Property<string>("UserRoles")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("user_roles");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("competitions_teams", b =>
                {
                    b.Property<long>("competition_id")
                        .HasColumnType("bigint");

                    b.Property<long>("team_id")
                        .HasColumnType("bigint");

                    b.HasKey("competition_id", "team_id");

                    b.HasIndex("team_id");

                    b.ToTable("competitions_teams", (string)null);
                });

            modelBuilder.Entity("Soccer.Server.Models.Competitions", b =>
                {
                    b.HasOne("Soccer.Server.Models.User", "Creator")
                        .WithMany("UserCompetitionsCreated")
                        .HasForeignKey("creator_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Soccer.Server.Models.Match", b =>
                {
                    b.HasOne("Soccer.Server.Models.Teams", "AwayTeam")
                        .WithMany("AwayMatches")
                        .HasForeignKey("away_team_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Soccer.Server.Models.Competitions", "Competition")
                        .WithMany("CompetitionsMetches")
                        .HasForeignKey("competition_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Soccer.Server.Models.Teams", "HomeTeam")
                        .WithMany("HomeMatches")
                        .HasForeignKey("home_team_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("Competition");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("Soccer.Server.Models.Participant", b =>
                {
                    b.HasOne("Soccer.Server.Models.Competitions", "Competition")
                        .WithMany("CompetitionParticipants")
                        .HasForeignKey("competition_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Soccer.Server.Models.Teams", "Team")
                        .WithMany("MembersInTeam")
                        .HasForeignKey("members_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Soccer.Server.Models.User", "User")
                        .WithMany("UserParticipations")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Soccer.Server.Models.Posts", b =>
                {
                    b.HasOne("Soccer.Server.Models.User", "User")
                        .WithMany("UserPosts")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Soccer.Server.Models.Recipe", b =>
                {
                    b.HasOne("Soccer.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Soccer.Server.Models.Teams", b =>
                {
                    b.HasOne("Soccer.Server.Models.User", "Owner")
                        .WithMany("OwnedTeams")
                        .HasForeignKey("owner_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("competitions_teams", b =>
                {
                    b.HasOne("Soccer.Server.Models.Competitions", null)
                        .WithMany()
                        .HasForeignKey("competition_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Soccer.Server.Models.Teams", null)
                        .WithMany()
                        .HasForeignKey("team_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Soccer.Server.Models.Competitions", b =>
                {
                    b.Navigation("CompetitionParticipants");

                    b.Navigation("CompetitionsMetches");
                });

            modelBuilder.Entity("Soccer.Server.Models.Teams", b =>
                {
                    b.Navigation("AwayMatches");

                    b.Navigation("HomeMatches");

                    b.Navigation("MembersInTeam");
                });

            modelBuilder.Entity("Soccer.Server.Models.User", b =>
                {
                    b.Navigation("OwnedTeams");

                    b.Navigation("UserCompetitionsCreated");

                    b.Navigation("UserParticipations");

                    b.Navigation("UserPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
